server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/api/tools/**, /api/tool-items/**, /api/categories/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: tariff-service
          uri: lb://tariff-service
          predicates:
            - Path=/api/tariffs/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # En local usas localhost, en Minikube usarás el nombre del servicio
            issuer-uri: http://localhost:8085/realms/ToolRent
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: zMYHsXfBqJ3lDhGoaOp0iGUnsTHGVOjJ
            scope: openid, profile, email